export { LoginPage } from './Login';
export { RegistrationPage } from './Registration';
export { ChatsPage } from './ChatsPage';
export { ProfilePage } from './Profile';
export { ProfileEditPage } from './ProfileEdit';
export { ProfileEditPasswordPage } from './ProfileEditPassword';
export { Page500 } from './Page500';
export { Page404 } from './Page404';
export { PageWithModal } from './PageWithModal';
